Fix untyped properties to Json per swagger spec
swagger-codegen added UntypedProperty after version 1.0.32 which we
didn't handle and this caused issues with code generation no longer
properly reporting errors, just having a generic:

Error: Unable to resolve type for null (null null null null)

I took a look at the code that was added and what other implementations
did: https://github.com/swagger-api/swagger-core#2507

For all the Scala code generators, they either returned Any (Akka, Scala, etc)
or Object (finch). Though, how could we create an encoder/decoder for such an
arbitrary type in any meaningful way?

It appears in the case of additionalProperties and any other json schema
proprty, all that is required is valid json. Since there is no actual
type that we can infer from an untyped it makes sense to return the most
specific type we can: Json. In this case, we are returning io.circe.Json